/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register_design;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mirza
 */
public class Delete_Training_Material extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Training_Material
     */
    public Delete_Training_Material() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1_exit = new javax.swing.JButton();
        jButton2_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1_trMaterialList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Delete Training Material");

        jButton1_exit.setText("Exit");
        jButton1_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_exitActionPerformed(evt);
            }
        });

        jButton2_delete.setText("Delete");
        jButton2_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_deleteMouseClicked(evt);
            }
        });
        jButton2_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_deleteActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1_trMaterialList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_exit)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_exit)
                    .addComponent(jButton2_delete))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_exitActionPerformed
        // TODO add your handling code here:
        new ManageTrainingMaterialsOptions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1_exitActionPerformed

    private void jButton2_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_deleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int programID = GetProgramIDByTrainerID(User._LoginUser.id);
        var list = GetAllTrainingMaterialByProgramID(programID);

        var listModel = new DefaultListModel();
        for (int i = 0; i < list.size(); i++) {
            listModel.add(i, list.get(i));
        }
        jList1_trMaterialList.setModel(listModel);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_deleteMouseClicked
        String trMaterialTopic = jList1_trMaterialList.getSelectedValue();
        if (jList1_trMaterialList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a topic!");
            this.setVisible(false);
            this.setVisible(true);
        }
        if (!jList1_trMaterialList.isSelectionEmpty()) {
            int trMaterialID = getTrMaterialIDByTopic(trMaterialTopic);
            deleteTrainingMaterialByTrMaterialTopic(trMaterialTopic, trMaterialID);
            JOptionPane.showMessageDialog(null, "Training Material Deleted Successfully!");
            new ManageTrainingMaterialsOptions().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButton2_deleteMouseClicked

    public int GetProgramIDByTrainerID(int trainerID) {
        String databaseURL = "jdbc:derby://localhost:1527/TMS";
        try ( Connection conn = DriverManager.getConnection(databaseURL, "root", "123123")) {
            Statement sta = conn.createStatement();
            int programID = 0;

            if (conn != null) {
                ResultSet res = sta.executeQuery(
                        "SELECT ROOT.TRAINER_TRAINING_PROGRAM.PROGRAM_ID\n"
                        + "FROM ROOT.TRAINER_TRAINING_PROGRAM\n"
                        + "WHERE ROOT.TRAINER_TRAINING_PROGRAM.TRAINER_ID = " + trainerID);

                if (res != null) {
                    while (res.next()) {
                        programID = res.getInt("PROGRAM_ID");
                    }
                    res.close();
                    sta.close();
                    conn.close();
                    return programID;
                }

                res.close();
                sta.close();
                conn.close();
                return 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
        return 0;
    }

    public List<String> GetAllTrainingMaterialByProgramID(int programID) {
        String databaseURL = "jdbc:derby://localhost:1527/TMS";
        List<String> list = new ArrayList<String>();
        try ( Connection conn = DriverManager.getConnection(databaseURL, "root", "123123")) {
            Statement sta = conn.createStatement();

            if (conn != null) {
                ResultSet res = sta.executeQuery(
                        "SELECT ROOT.TRAINING_MATERIAL.TRMATERIAL_TOPIC\n"
                        + "FROM ROOT.TRAINING_PROGRAM_TRAINING_MATERIAL\n"
                        + "LEFT JOIN ROOT.TRAINING_MATERIAL\n"
                        + "ON ROOT.TRAINING_MATERIAL.TRMATERIAL_ID = ROOT.TRAINING_PROGRAM_TRAINING_MATERIAL.TRMATERIAL_ID\n"
                        + "WHERE ROOT.TRAINING_PROGRAM_TRAINING_MATERIAL.PROGRAM_ID = " + programID);

                if (res != null) {
                    while (res.next()) {
                        var name = res.getString("TRMATERIAL_TOPIC");
                        list.add(name);
                    }
                    res.close();
                    sta.close();
                    conn.close();
                    return list;
                }

                res.close();
                sta.close();
                conn.close();
                return null;
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
        return null;
    }

    public int getTrMaterialIDByTopic(String topic) {
        String databaseURL = "jdbc:derby://localhost:1527/TMS";
        try ( Connection conn = DriverManager.getConnection(databaseURL, "root", "123123")) {
            Statement sta = conn.createStatement();
            int trMaterialID = 0;

            if (conn != null) {
                ResultSet res = sta.executeQuery(
                        "SELECT ROOT.TRAINING_MATERIAL.TRMATERIAL_ID \n"
                        + "FROM ROOT.TRAINING_MATERIAL \n"
                        + "where ROOT.TRAINING_MATERIAL.TRMATERIAL_TOPIC = '" + topic + "'");

                if (res != null) {
                    while (res.next()) {
                        trMaterialID = res.getInt("TRMATERIAL_ID");
                    }
                    res.close();
                    sta.close();
                    conn.close();
                    return trMaterialID;
                }

                res.close();
                sta.close();
                conn.close();
                return 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
        return 0;
    }

    public void deleteTrainingMaterialByTrMaterialTopic(String trMaterialTopic, int trMaterialID) {
        String databaseURL = "jdbc:derby://localhost:1527/TMS";
        try ( Connection conn = DriverManager.getConnection(databaseURL, "root", "123123")) {
            Statement sta = conn.createStatement();

            if (conn != null) {
                sta.executeUpdate(
                        "DELETE FROM ROOT.TRAINING_MATERIAL \n"
                        + "WHERE ROOT.TRAINING_MATERIAL.TRMATERIAL_TOPIC = '" + trMaterialTopic + "'");

                sta.executeUpdate("DELETE FROM ROOT.TRAINING_PROGRAM_TRAINING_MATERIAL \n"
                        + "WHERE ROOT.TRAINING_PROGRAM_TRAINING_MATERIAL.TRMATERIAL_ID = " + trMaterialID);
                sta.close();
                conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Training_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Training_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Training_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Training_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Training_Material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_exit;
    private javax.swing.JButton jButton2_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1_trMaterialList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
